name: Get BW secets

permissions:
      contents: write
      pull-requests: write
      id-token: write

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.repository}}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
 build-and-test:
  runs-on: macos-latest
  steps:
#    - name: Install jq (for parsing) and unzip
#      run: brew install jq unzip
    - name: Install Bitwarden Secrets Manager CLI (bws)
      run: |
        BWS_VERSION="1.0.0" # adjust to current release
        curl -L -o bws.zip "https://github.com/bitwarden/sdk/releases/download/bws-v${BWS_VERSION}/bws-aarch64-apple-darwin-${BWS_VERSION}.zip"
        unzip -q bws.zip -d /usr/local/bin
        chmod +x /usr/local/bin/bws
        bws --version
    - name: Get Secrets via bws
      env:
        BWS_ACCESS_TOKEN: ${{ secrets.BW_ACCESS_TOKEN }}
      run: |
        bws secret get 9bb4989-b39f-43a3-bc4d-b361011cbb23 >> $GITHUB_ENV
        bws secret get 165e90ae-bed4-41bb-9ec0-b361011ba441 >> $GITHUB_ENV
        bws secret get 2afaa8d6-cadf-45c9-bdbb-b361011ba3f0 >> $GITHUB_ENV
        bws secret get acef0f47-efa1-4036-9584-b361011ba349 >> $GITHUB_ENV
        bws secret get e70fbaf0-de89-4a23-a70b-b361011ba3a1 >> $GITHUB_ENV
    - name: dump
      run: env

    
